spring:
  application:
    name: delivery-tracking
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://192.168.0.13:5432/deliverydb
    username: postgres
    password: postgres